### ISSUE TITLE
Update AWS SDK dependencies

### ISSUE THREAD

**Issue by MrZoidberg** [milestonetg/extensions-configuration-s3#2]
Hey,

I've started to use your library, however, it has a conflict with the latest AWS SDK nuget package versions. I can create PR to update them to the latest versions or I can try to use ignore minor and patch versions of those libs like `<PackageReference Include="AWSSDK.S3" Version="3.3.*.*" />`. However, the latest versions are 3.5, so a bump is still needed.

What do you think?

**Comment by AuroraDysis** [comment]
I meet the same problem, ping @jpenniman

**Comment by jpenniman** [comment]
In your application, just reference the latest version of the SDK. There shouldn't be any issues. Dependency redirection is a common/necessary thing in .Net.  Recommended best practice is to depend on the minimum version required for the functionality being used and not to force consumers to always use the latest version.

.Net Framework
https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/redirect-assembly-versions

.Net Core/.Net 5/6
Simply reference the latest version in your application.

Are their breaking changes in AWSSDK 3.5.x that are causing an issue?

**Comment by AuroraDysis** [comment]
Hello, here is the log of nuget
```
Restoring packages for xxxxxx
NU1107: Version conflict detected for AWSSDK.Core. Install/reference AWSSDK.Core 3.7.3.20 directly to project xxxxxx to resolve this issue. 
 xxxxxx -> AWSSDK.S3 3.7.3.13 -> AWSSDK.Core (>= 3.7.3.20 && < 4.0.0) 
 xxxxxx-> MilestoneTG.Extensions.Configuration.S3 1.2.0 -> AWSSDK.Extensions.NETCore.Setup 3.3.6 -> AWSSDK.Core (>= 3.3.13.3 && < 3.4.0).
Package restore failed. Rolling back package changes for 'xxxxxx'.
```

**Comment by jpenniman** [comment]
Did you do what the error suggests for the fix? That's how you do assembly redirects in .Net Core/5/6.  Add this to your project XXXXX as suggested by the error message (these are the latest versions as of this post):

``` xml
<PackageReference Include="AWSSDK.Core" Version="3.7.3.22" />
<PackageReference Include="AWSSDK.Extensions.NETCore.Setup" Version="3.7.1" />
<PackageReference Include="AWSSDK.S3" Version="3.7.3.15" />
```

The issue is, an AWS SDK that you are using has a dependency on a newer version of `AWSSDK.Core`. So it needs to be explicitly referenced. Nuget doesn't coalesce or redirect implicit dependencies.  The version of `AWSSDK.Extensions.NETCore.Setup` our S3 package uses won't allow a version higher than 3.3.x, so the matching version of that needs to be referenced as well.

**Comment by AuroraDysis** [comment]
I see, thank you very much for your help.

**Comment by jpenniman** [comment]
You're welcome. Let me know how it goes.

**Comment by AuroraDysis** [comment]
It works very well. I've never noticed this before. Thanks again.
